LabaratuvarYonetimSistemi/LabaratuvarYonetimSistemi/Controllers/KullanicilarController.cs
using LabaratuvarYonetimSistemi.Fonksiyonlar;
using LabaratuvarYonetimSistemi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace LabaratuvarYonetimSistemi.Controllers
{
    public class KullanicilarController : Controller
    {
        Context db = new Context();
        Md5Pw md5 = new Md5Pw();
        Ziyaretci_Log Ziyaretci_Log = new Ziyaretci_Log();
        public ActionResult Index()
        {
            Session["tur"] = 1;
            Session["name"] = "oğuzhan";

            //if (Session["id"] == null) return RedirectToAction("Giris");
            return View();
        }
        public ActionResult IndexAra()
        {
            Session["tur"] = 1;
            Session["name"] = "oğuzhan";

            //if (Session["id"] == null) return RedirectToAction("Giris");
            return View();
        }


        public ActionResult Giris()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Giris(Kullanici p)
        {
            p.KullaniciParolasi = md5.MD5(p.KullaniciParolasi);
            var gelenKayit = db.Kullanici.Where(x => x.KullaniciAd == p.KullaniciAd && x.KullaniciParolasi == p.KullaniciParolasi && x.Aktif == true).FirstOrDefault();
            if (gelenKayit != null)
            {
                string bilgisayarAdi = Dns.GetHostName();
                string ipAdresi = Dns.GetHostByName(bilgisayarAdi).AddressList[0].ToString();
                Session["id"] = gelenKayit.KullaniciID;
                Session["name"] = gelenKayit.Ad;
                Session["soyad"] = gelenKayit.Soyad;
                Session["tur"] = gelenKayit.KullaniciTuru;

                // ZİYARETÇİ TABLOSUNA EKLEME
                //Ziyaretci z = new Ziyaretci();
                //z.KullaniciNo = gelenKayit.KullaniciID;
                //z.KullaniciAd = gelenKayit.KullaniciAd;
                //z.Ad = gelenKayit.Ad;
                //z.Soyad = gelenKayit.Soyad;
                //z.SicilNo = gelenKayit.SicilNo;
                //z.KullaniciTuru = gelenKayit.KullaniciTuru;
                //z.GirisIP = ipAdresi;
                //z.GirisZamani = DateTime.Now.ToString();
                //db.Ziyaretci.Add(z);
                //db.SaveChanges();

                Ziyaretci_Log.ZiyaretciEkle(gelenKayit, ipAdresi);


                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "Kullanıcı adı veya şifre hatalı";
                TempData["icon"] = "error";
                return View();
            }
        }


        public PartialViewResult FormKullanici()
        {
            return PartialView();
        }
        public PartialViewResult FormKullaniciDuzenle()
        {
            var kullaniciListesi = db.Kullanici.ToList();
            return PartialView(kullaniciListesi);
        }
        public PartialViewResult Ara()
        {
            return PartialView();
        }
        public PartialViewResult Tablo()
        {
            var kullaniciListesi = db.Kullanici.ToList();
            return PartialView(kullaniciListesi);
        }
        public PartialViewResult TabloAra()
        {

            return PartialView();
        }


        [HttpPost]
        public ActionResult KullaniciEkle(Kullanici p)
        {
            string bilgisayarAdi = Dns.GetHostName();
            string ipAdresi = Dns.GetHostByName(bilgisayarAdi).AddressList[0].ToString();
            p.KullaniciParolasi = md5.MD5(p.KullaniciParolasi);
            p.EklemeZamani = DateTime.Now.ToString();
            p.GuncellemeZamani = DateTime.Now.ToString();
            p.GuncelleyenIP = ipAdresi;
            p.GuncelleyenBilgisi = Session["id"].ToString() + " - " + Session["name"] + " " + Session["soyad"];
            db.Kullanici.Add(p);
            db.SaveChanges();
            TempData["message"] = "İşlem Başarılı";
            TempData["icon"] = "success";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult KullaniciGuncelle(Kullanici p)
        {
            string bilgisayarAdi = Dns.GetHostName();
            string ipAdresi = Dns.GetHostByName(bilgisayarAdi).AddressList[0].ToString();
            var gelenKayit = db.Kullanici.Find(p.KullaniciID);
            gelenKayit.KullaniciAd = p.KullaniciAd;
            gelenKayit.Ad = p.Ad;
            gelenKayit.Soyad = p.Soyad;
            gelenKayit.SicilNo = p.SicilNo;
            gelenKayit.Eposta = p.Eposta;
            gelenKayit.Telefon = p.Telefon;
            gelenKayit.KullaniciTuru = p.KullaniciTuru;
            gelenKayit.Aktif = p.Aktif;
            gelenKayit.GuncellemeZamani = DateTime.Now.ToString();
            gelenKayit.GuncelleyenIP = ipAdresi;
            gelenKayit.GuncelleyenBilgisi = Session["id"].ToString() + " - " + Session["name"] + " " + Session["soyad"];
            db.SaveChanges();
            TempData["message"] = "İşlem Başarılı";
            TempData["icon"] = "success";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Sil(int id)
        {
            var gelenKayit = db.Kullanici.Find(id);
            db.Kullanici.Remove(gelenKayit);
            db.SaveChanges();
            TempData["message"] = "İşlem Başarılı";
            TempData["icon"] = "success";
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult KullaniciAra(Kullanici p)
        {
            if (p.KullaniciAd == null) p.KullaniciAd = "";
            if (p.Ad == null) p.Ad = "";
            if (p.Soyad == null) p.Soyad = "";
            if (p.SicilNo == null) p.SicilNo = "";
            if (p.Eposta == null) p.Eposta = "";
            if (p.Telefon == null) p.Telefon = "";
            var kullanicilar = db.Kullanici.ToList();
            List<Kullanici> arananListe = new List<Kullanici>();
            if (p.KullaniciTuru != 0)
                arananListe = kullanicilar.Where(i => i.KullaniciAd.Contains(p.KullaniciAd) && i.Ad.Contains(p.Ad) &&
                i.Soyad.Contains(p.Soyad) && i.SicilNo.Contains(p.SicilNo) &&
                i.Eposta.Contains(p.Eposta) && i.Telefon.Contains(p.Telefon) && i.KullaniciTuru == p.KullaniciTuru
                && i.Aktif == p.Aktif).ToList();
            else
                arananListe = kullanicilar.Where(i => i.KullaniciAd.Contains(p.KullaniciAd) && i.Ad.Contains(p.Ad) &&
                i.Soyad.Contains(p.Soyad) && i.SicilNo.Contains(p.SicilNo) &&
                i.Eposta.Contains(p.Eposta) && i.Telefon.Contains(p.Telefon)
                && i.Aktif == p.Aktif).ToList();


            
            TempData["liste"] = arananListe;
            TempData["model"] = p;
            return RedirectToAction("IndexAra");
        }

        public ActionResult AktiflikAyari(int id)
        {
            var gelenKayit = db.Kullanici.Find(id);
            if (gelenKayit.Aktif)
                gelenKayit.Aktif = false;

            else gelenKayit.Aktif = true;
            db.SaveChanges();
            TempData["message"] = "İşlem Başarılı";
            TempData["icon"] = "success";
            return RedirectToAction("Index");
        }
    }
}

LabaratuvarYonetimSistemi/LabaratuvarYonetimSistemi/Views/Kullanicilar/Ara.cshtml
<!-- /.row -->

<div class="col-4">
    <form method="post" action="/Kullanicilar/KullaniciAra">
        <div class="card">
            <div class="card-header" style="background-color:#f59a2b" onclick="AcKapa2()">
                <p class="card-title"><b>Ara</b></p>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="body2">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kullanıcı Adı</label>
                            <input type="text" class="form-control" name="KullaniciAd">
                            <!-- /.card-body -->
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="form-group">
                            <label>Adı</label>
                            <input type="text" class="form-control" name="Ad">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Soyadı</label>
                            <input type="text" class="form-control" name="Soyad">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kurum Sicil Numarası</label>
                            <input type="text" class="form-control" name="SicilNo">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>E posta</label>
                            <input type="email" class="form-control" name="Eposta">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Telefon</label>
                            <input type="text" class="form-control" name="Telefon" maxlength="11">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kullanıcı Türü</label>
                            <select class="form-control select2" style="width: 100%;" name="KullaniciTuru">
                                <option value="0">Tümü</option>
                                <option value="1">Teknik Destek</option>
                                <option value="2">Otomasyon Yöneticisi</option>
                                <option value="3">Operatör</option>
                            </select>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Aktif</label>
                            <br />
                            <input type="checkbox" name="Aktif" value="true" checked data-bootstrap-switch>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>


                <div class="card-footer info">
                    <button class="btn btn-app btn-info">
                        <i class="fas fa-search"></i> Ara
                    </button>
                </div>

            </div>

            <!-- /.card -->
        </div>
    </form>
</div>

<script>
    function AcKapa2() {
        $("#body2").animate({
            height: 'toggle'
        });
    }
</script>

LabaratuvarYonetimSistemi/LabaratuvarYonetimSistemi/Views/Kullanicilar/FormKullanici.cshtml
<!-- /.row -->

<div class="col-8 mainClass" id="col_YeniKullanici">
    <form method="post" action="/Kullanicilar/KullaniciEkle" >
        <div class="card">
            <div class="card-header" style="background-color:#1dadb6" onclick="AcKapa()">
                <p class="card-title"><b>Kullanıcı Ekle</b></p>
            </div>
            <!-- /.card-header -->
            <div class="card-body" id="body">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kullanıcı Adı</label>
                            <input type="text" class="form-control" name="KullaniciAd" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kullanıcı Parolası</label>
                            <input type="text" class="form-control" name="KullaniciParolasi" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Adı</label>
                            <input type="text" class="form-control" name="Ad" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Soyadı</label>
                            <input type="text" class="form-control" name="Soyad" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kurum Sicil Numarası</label>
                            <input type="text" class="form-control" name="SicilNo" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>E posta</label>
                            <input type="email" class="form-control" name="Eposta" required>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Telefon</label>
                            <input type="text" class="form-control" name="Telefon" maxlength="11">
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Kullanıcı Türü</label>
                            <select class="form-control select2" style="width: 100%;" name="KullaniciTuru">
                                <option value="1">Teknik Destek</option>
                                <option value="2">Otomasyon Yöneticisi</option>
                                <option value="3">Operatör</option>
                            </select>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>Aktif</label>
                            <br />
                            <input type="checkbox" name="Aktif" value="true" checked data-bootstrap-switch>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <div class="row">
                        <div class="col-6">
                            <button type="submit" class="btn btn-block btn-outline-info">Ekle</button>
                        </div>
                        <div class="col-6">
                            <button type="button" class="btn btn-block btn-outline-info" disabled>Güncelle</button>
                        </div>
                    </div>
                    <br />





                </div>

            </div>
            <!-- /.card -->
        </div>
    </form>
</div>


<script>

    // A $( document ).ready() block.
   
    function AcKapa() {
        $("#body").animate({
            height: 'toggle'
        });
    }
</script>

LabaratuvarYonetimSistemi/LabaratuvarYonetimSistemi/Views/Kullanicilar/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/fontawesome-free/css/all.min.css">
    <!-- daterange picker -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/daterangepicker/daterangepicker.css">
    <!-- iCheck for checkboxes and radio inputs -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
    <!-- BS Stepper -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/bs-stepper/css/bs-stepper.min.css">
    <!-- dropzonejs -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/dropzone/min/dropzone.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/dist/css/adminlte.min.css">

    <!-- DataTables -->
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/PANEL/AdminLTE-master/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
</head>
<body class="hold-transition sidebar-mini">
    @Html.Partial("~/Views/PageRequirement/Head.cshtml")
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Kullanıcılar</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">DataTables</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @if (int.Parse(Session["tur"].ToString()) == 1 || int.Parse(Session["tur"].ToString()) == 2)
                {
                    @Html.Action("FormKullanici", "Kullanicilar")
                    @Html.Action("FormKullaniciDuzenle", "Kullanicilar")
                }


                @Html.Action("Ara", "Kullanicilar")
                @Html.Action("Tablo", "Kullanicilar")

                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/PANEL/AdminLTE-master/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/PANEL/AdminLTE-master/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Select2 -->
    <script src="~/PANEL/AdminLTE-master/plugins/select2/js/select2.full.min.js"></script>
    <!-- Bootstrap4 Duallistbox -->
    <script src="~/PANEL/AdminLTE-master/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
    <!-- InputMask -->
    <script src="~/PANEL/AdminLTE-master/plugins/moment/moment.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/inputmask/jquery.inputmask.min.js"></script>
    <!-- date-range-picker -->
    <script src="~/PANEL/AdminLTE-master/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap color picker -->
    <script src="~/PANEL/AdminLTE-master/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/PANEL/AdminLTE-master/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Bootstrap Switch -->
    <script src="~/PANEL/AdminLTE-master/plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
    <!-- BS-Stepper -->
    <script src="~/PANEL/AdminLTE-master/plugins/bs-stepper/js/bs-stepper.min.js"></script>
    <!-- dropzonejs -->
    <script src="~/PANEL/AdminLTE-master/plugins/dropzone/min/dropzone.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/PANEL/AdminLTE-master/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/PANEL/AdminLTE-master/dist/js/demo.js"></script>
    <!-- Page specific script -->
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
                theme: 'bootstrap4'
            })

            //Datemask dd/mm/yyyy
            $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
            //Datemask2 mm/dd/yyyy
            $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
            //Money Euro
            $('[data-mask]').inputmask()

            //Date range picker
            $('#reservationdate').datetimepicker({
                format: 'L'
            });
            //Date range picker
            $('#reservation').daterangepicker()
            //Date range picker with time picker
            $('#reservationtime').daterangepicker({
                timePicker: true,
                timePickerIncrement: 30,
                locale: {
                    format: 'MM/DD/YYYY hh:mm A'
                }
            })
            //Date range as a button
            $('#daterange-btn').daterangepicker(
                {
                    ranges: {
                        'Today': [moment(), moment()],
                        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                        'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                        'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                        'This Month': [moment().startOf('month'), moment().endOf('month')],
                        'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                    },
                    startDate: moment().subtract(29, 'days'),
                    endDate: moment()
                },
                function (start, end) {
                    $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
                }
            )

            //Timepicker
            $('#timepicker').datetimepicker({
                format: 'LT'
            })

            //Bootstrap Duallistbox
            $('.duallistbox').bootstrapDualListbox()

            //Colorpicker
            $('.my-colorpicker1').colorpicker()
            //color picker with addon
            $('.my-colorpicker2').colorpicker()

            $('.my-colorpicker2').on('colorpickerChange', function (event) {
                $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
            });

            $("input[data-bootstrap-switch]").each(function () {
                $(this).bootstrapSwitch('state', $(this).prop('checked'));
            });

        })
        // BS-Stepper Init
        document.addEventListener('DOMContentLoaded', function () {
            window.stepper = new Stepper(document.querySelector('.bs-stepper'))
        });

        // DropzoneJS Demo Code Start
        Dropzone.autoDiscover = false;

        // Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
        var previewNode = document.querySelector("#template");
        previewNode.id = "";
        var previewTemplate = previewNode.parentNode.innerHTML;
        previewNode.parentNode.removeChild(previewNode);

        var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
            url: "/target-url", // Set the url
            thumbnailWidth: 80,
            thumbnailHeight: 80,
            parallelUploads: 20,
            previewTemplate: previewTemplate,
            autoQueue: false, // Make sure the files aren't queued until manually added
            previewsContainer: "#previews", // Define the container to display the previews
            clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
        });

        myDropzone.on("addedfile", function (file) {
            // Hookup the start button
            file.previewElement.querySelector(".start").onclick = function () { myDropzone.enqueueFile(file); };
        });

        // Update the total progress bar
        myDropzone.on("totaluploadprogress", function (progress) {
            document.querySelector("#total-progress .progress-bar").style.width = progress + "%";
        });

        myDropzone.on("sending", function (file) {
            // Show the total progress bar when upload starts
            document.querySelector("#total-progress").style.opacity = "1";
            // And disable the start button
            file.previewElement.querySelector(".start").setAttribute("disabled", "disabled");
        });

        // Hide the total progress bar when nothing's uploading anymore
        myDropzone.on("queuecomplete", function (progress) {
            document.querySelector("#total-progress").style.opacity = "0";
        });

        // Setup the buttons for all transfers
        // The "add files" button doesn't need to be setup because the config
        // `clickable` has already been specified.
        document.querySelector("#actions .start").onclick = function () {
            myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED));
        };
        document.querySelector("#actions .cancel").onclick = function () {
            myDropzone.removeAllFiles(true);
        };
        // DropzoneJS Demo Code End</script>

    <!-- DataTables  & Plugins -->
    <script src="~/PANEL/AdminLTE-master/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/jszip/jszip.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/PANEL/AdminLTE-master/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>

</body>
</html>